@extends('frontend/layouts.app')
@section('content')


<section class="terms" style="margin-top: 80px;">
    <div class="container">
        <p><strong><u>BASES Y CONDICIONES DEL CONCURSO: &ldquo;HEINEKEN CHAMPIONS 2022</u></strong><strong>&rdquo;</strong></p>
        <ol>
            <li>Compa&ntilde;&iacute;a Industrial Cervecera S.A. (el adelante el &ldquo;Organizador&rdquo;), CUIT N&ordm;&nbsp;30-50577985-8, con domicilio en&nbsp; Calchines 1401, (CP 3000) Santa Fe, provincia de Santa Fe,el concurso denominado &ldquo;Promo Heineken Champions&rdquo; (en adelante el &ldquo;Concurso&rdquo;)&nbsp;y que se regir&aacute; por lo establecido en estas bases y condiciones (en adelante las &ldquo;Bases&rdquo;).</li> <br>
            <li><strong><u>Validez y Vigencia</u></strong><strong><u>:</u></strong> El Concurso se desarrollar&aacute; en todo el territorio de la Rep&uacute;blica Argentina excepto las provincias de Mendoza, R&iacute;o Negro, Salta y Tierra del Fuego(en adelante el &ldquo;Territorio&rdquo;),&nbsp;desde el 08 de abril de 2022 al 20 de mayo de 2022 inclusive <strong><em>(en adelanta el &ldquo;Plazo de Vigencia</em></strong><strong><em>&rdquo;)</em></strong><strong><em>.</em></strong> Este plazo de vigencia es improrrogable, no acept&aacute;ndose en consecuencia participaciones posteriores a la finalizaci&oacute;n del Plazo de Vigencia del Concurso.</li> <br>
            <li><strong><u>Participantes:</u></strong> Podr&aacute;n participar en el Concurso las personas humanas, mayores de 18 a&ntilde;os, domiciliadas en el Territorio, que cumplan con el mecanismo de participaci&oacute;n indicado en estas Bases (en adelante &ldquo;Participantes&rdquo;). No podr&aacute;n participar personas jur&iacute;dicas, los empleados del Organizador, de sus sociedades vinculadas, de sus agencias de promoci&oacute;n y publicidad, de los proveedores de envases y de tapas de los Productos, repositores de mercader&iacute;a ni tampoco los c&oacute;nyuges, los parientes por consanguinidad o afinidad hasta el segundo grado inclusive de cualquiera de los anteriores ni sus c&oacute;nyuges, sea que lo hagan en nombre propio o de terceros.</li> <br>
            <li><strong><u>Modo de Participaci&oacute;n:</u></strong> Para participar en el Concurso los Participantes deber&aacute;n, durante el Plazo de Vigencia: (i) Ingresar al sitio Web:&nbsp;<a target="_blank" href="https://www.heineken.com/ar/es/champions">https://www.heineken.com/ar/es/champions</a>; (ii) Registrar los datos personales all&iacute; requeridos (en adelante los &ldquo;Datos Personales&rdquo;); (iii) Elegir su equipo favorito y responder de manera creativa y divertida la pregunta: &ldquo;&iquest;Qu&eacute; har&iacute;as para ganarte el viaje a la final?&rdquo; (en adelante la &ldquo;Pregunta&rdquo;). Las respuestas a la Pregunta deben ser de creaci&oacute;n propia e in&eacute;dita. Al cumplir con la mec&aacute;nica dispuesta en los puntos (i) a (iv) precedentes, los Participantes autom&aacute;ticamente estar&aacute;n participando del Concurso en los t&eacute;rminos de las presentes Bases por los premios detallados en la cl&aacute;usula 8.</li>
        </ol>
        <p>Ser&aacute;n descalificados los Participantes que no completen los Datos Personales, los que no los completen correctamente, los que hubieran proporcionado Datos Personales que fueran falsos, inexactos y/o incompletos,&nbsp;y/o los que no respondan la Pregunta. Asimismo, ser&aacute;n descalificados los Participantes cuyas respuestas a la Pregunta pudieran ser consideradas, a exclusivo criterio del Organizador, ofensivas, discriminatorias o contrarias a la ley y/o a la moral y/o a las buenas costumbres y/o que no sean propias e in&eacute;ditas.</p>
        <p>Una vez cumplidos los requisitos enunciados en los puntos (i) a (iii) precedentes, los Participantes quedar&aacute;n autom&aacute;ticamente registrados en el Concurso.</p>
        <ol start="5">
            <li><strong><u>Selecci&oacute;n de ganadores:</u></strong></li>
        </ol>
        <p>Un jurado designado por el Organizador (en adelante el &ldquo;Jurado&rdquo;) elegir&aacute; &ndash;a su exclusivo criterio- a los ganadores del Concurso, adoptando como criterio de selecci&oacute;n la creatividad y diversi&oacute;n de las respuestas a la Pregunta brindadas por los Participantes, y con ese mismo criterio ser&aacute;n asignados los premios entre los que resultaren ganadores. El ganador m&aacute;ximo del Concurso ser&aacute; aquel participante que hubiera proporcionado &ndash;a criterio del Jurado- la respuesta m&aacute;s creativa y divertida de todas las respuestas a la Pregunta brindadas por los Participantes del Concurso, quien resultar&aacute; acreedor del premio m&aacute;ximo &ldquo;Viaje a la Final&rdquo; (conforme dicho t&eacute;rmino se define m&aacute;s abajo en las presentes Bases&rdquo;) (en adelante el &ldquo;Potencial Ganador M&aacute;ximo&rdquo;). Asimismo, el Jurado designar&aacute; otros 16 ganadores cada semana, que ser&aacute;n acreedores de los premios adicionales semanales (en adelante los &ldquo;Potenciales Ganadores&rdquo;). Los Potenciales Ganadores ser&aacute; elegidos por el Jurado entre aquellos Participantes que hubieran efectuado las respuestas a la Pregunta m&aacute;s creativas y divertidas de cada semana durante el Plazo de Vigencia. El Jurado definir&aacute; la asignaci&oacute;n de los premios adicionales en favor de los Potenciales Ganadores. La decisi&oacute;n del Jurado en materia de selecci&oacute;n del Potencial M&aacute;ximo Ganador y de los Potenciales Ganadores, como as&iacute; tambi&eacute;n de la asignaci&oacute;n de los premios adicionales en favor de los Ganadores, ser&aacute; definitiva e inapelable.</p>
        <p>El Potencial Ganador M&aacute;ximo ser&aacute; seleccionado por el Jurado el d&iacute;a 20 de Mayo. Los Potenciales Ganadores ser&aacute;n seleccionados por el Jurado los d&iacute;as viernes de cada semana durante el Plazo de Vigencia. El Jurado seleccionar&aacute; 16 Potenciales Ganadores cada semana durante el Plazo de Vigencia. Los Potenciales Ganadores elegidos no ser&aacute;n considerados las semanas siguientes como posible nuevos Potenciales Ganadores</p>
        <ol start="6">
            <li><strong><u>Notificaci&oacute;n:</u></strong> El Organizador notificar&aacute; al correo electr&oacute;nico proporcionado al momento de registrarse, a los Participantes que hayan sido elegidos por el Jurado como Potencial Ganador M&aacute;ximo y Potenciales Ganadores dentro de las 72 horas de haber sido seleccionados, a efectos de: (i) que el Potencial Ganador M&aacute;ximo y/o los Potenciales acepten el premio otorgado; (ii) coordinar la entrega de los premios. Si por cualquier causa no fuere posible contactar a al Potencial Ganador M&aacute;ximo y/o a los Potenciales Ganadores y/o que estos no dieran respuesta a fin de aceptar el premio otorgado dentro de las 72 horas posteriores a haber sido notificados, perder&aacute;n todo derecho al premio correspondiente, el mismo quedar&aacute; en poder del Organizador y dicho Participante nada tendr&aacute; que reclamar al Organizador.</li>
        </ol>
        <ol start="7">
            <li><strong><u>Asignaci&oacute;n y Entrega:</u></strong>Ser&aacute; condici&oacute;n esencial e ineludible para la entrega de cualquiera de los premios: (i) la acreditaci&oacute;n de identidad del Potencial Ganador; (ii) que el Potencial Ganador M&aacute;ximo y/o los Potenciales Ganadores firmen la documentaci&oacute;n legal que requiera el Organizador sobre cesi&oacute;n gratuita del uso de imagen y datos del ganador; y (iii) que el Potencial Ganador M&aacute;ximo y/o los Potenciales Ganadores cumplan y hayan cumplido con todas y cada una de los t&eacute;rminos y las condiciones establecidas en estas Bases. Habiendo cumplido con dichos recaudos, el Potencial Ganador M&aacute;ximo devendr&aacute; en ganador m&aacute;ximo (en adelante el &ldquo;Ganador M&aacute;ximo&rdquo;) y los Potenciales Ganadores en ganadores (en adelante el/los &ldquo;Ganador/es&rdquo; seg&uacute;n corresponda).</li>
        </ol>
        <p>El premio asignado &ldquo;Viaje a la Final&rdquo; (conforme se define dicho t&eacute;rmino en el punto 8 (i)) en favor del Ganador M&aacute;ximo ser&aacute; entregado personalmente en las oficinas del Organizador. Ser&aacute; condici&oacute;n para la entrega del premio la firma por parte del M&aacute;ximo Ganador del correspondiente recibo de recepci&oacute;n del premio.</p>
        <p>Los Premios Adicionales ser&aacute;n enviados dentro de los 7 (siete) d&iacute;as h&aacute;biles siguientes a la finalizaci&oacute;n del Plazo de Vigencia del Concurso y ser&aacute;n entregados en la direcci&oacute;n proporcionada por los Ganadores al momento de coordinar la entrega del premio conforme punto 6. de estas Bases. Ser&aacute; condici&oacute;n para la entrega del premio la firma por parte del Ganador del correspondiente recibo de recepci&oacute;n del premio.</p>
        <p>Si por alguna raz&oacute;n no imputable al Organizador, el Ganador M&aacute;ximo y/o los Ganadores se vieran imposibilitados de la utilizaci&oacute;n del premio obtenido, nada tendr&aacute;n que reclamar al Organizador, ni se realizara reembolso o cambio alguno.</p>
        <p>Si por cualquier causa quedaran premios sin asignar luego de terminado el Concurso, los mismos quedar&aacute;n en manos del Organizador.</p>
        <ol start="8">
            <li><strong><u>Premios:</u></strong>El programa total de premios puesto en juego en este Concurso ser&aacute; el siguiente (en adelante los &ldquo;Premios&rdquo;):</li>
        </ol>
        <p><strong><u>(i) Premio &ldquo;Viaje a la Final&rdquo;.</u></strong></p>
        <p><strong>a.- </strong>El Ganador M&aacute;ximo ser&aacute; acreedor de un viaje para dos personas para ver la final de la UEFA Champions League en el Estadio Stade de France de Paris (en adelante el &ldquo;Viaje a la Final&rdquo; y/o el &ldquo;Viaje&rdquo; indistintamente): El Viaje a la Final incluye dos (2) pasajes a&eacute;reos, de ida y vuelta, en clase turista/econ&oacute;mica, desde Ezeiza, provincia de Buenos Aires y con destino final la Ciudad de Par&iacute;s, con o sin escalas, en aerol&iacute;nea a definir por el Organizador, transportes desde el Aeropuerto de Par&iacute;s al hotel, y del Hotel al Estadio Stade de France, hospedaje en habitaci&oacute;n doble en hotel a definir por el Organizador, con desayuno, almuerzo, cena, y bebidas y dos (2) tickets para la final de la Copa UEFA Champions League a disputarse enel Stade de France.&nbsp;El Viaje&nbsp;deber&aacute; llevarse a cabo, indefectiblemente, en la &uacute;ltima semana de mayo (la final est&aacute; prevista seg&uacute;n organizadores para el 28/5/2022), en las fechas que establezca el Organizador y comunique a trav&eacute;s del Sitio Web y/o e-mail al Ganador M&aacute;ximo.El Ganador M&aacute;ximo no tendr&aacute; derecho a requerir cambios de fechas del Viaje por lo que si no aceptase viajar en las fechas propuestas por el Organizador perder&aacute; autom&aacute;ticamente todo derecho al Viaje a la Final, sin derecho a reclamo o compensaci&oacute;n alguna y/o a solicitar un reemplazo del premio asignado por otro. Las tasas aeroportuarias, las tasas e impuestos de embarque, las tasas de seguridad y de migraci&oacute;n, las tasas que deban pagarse en el lugar de destino, as&iacute; como todos los dem&aacute;s costos relacionados con la efectivizaci&oacute;n del Viaje no incluidos en la enumeraci&oacute;n precedente &ndash;incluyendo, pero no limitado, al traslado del ganador y acompa&ntilde;ante hasta y desde el Aeropuerto internacional de Ezeiza, comidas, propinas, seguro de viaje de asistencia al viajero, seguro m&eacute;dico y llamadas telef&oacute;nicas - estar&aacute;n tambi&eacute;n a cargo del Ganador M&aacute;ximo y su acompa&ntilde;ante. Asimismo, Ser&aacute; de exclusiva responsabilidad del Ganador M&aacute;ximo y de su acompa&ntilde;ante &ndash; y requisito para la asignaci&oacute;n del Viaje &ndash; que obtengan la documentaci&oacute;n necesaria para salir de la Rep&uacute;blica Argentina e ingresar y permanecer en el pa&iacute;s de destino con una anticipaci&oacute;n suficiente para la realizaci&oacute;n del Viaje, caso contrario el Ganador M&aacute;ximo perder&aacute; autom&aacute;ticamente todo derecho a su asignaci&oacute;n, sin derecho a reclamo o compensaci&oacute;n alguna. Todos los costos que se deriven de ello estar&aacute;n asimismo a cargo del Ganador M&aacute;ximo y su acompa&ntilde;ante.</p>
        <p><strong><u>b.- Premios Adicionales:</u></strong></p>
        <p>La asignaci&oacute;n de los Premios Adicionales en favor de los Potenciales Ganadores ser&aacute; efectuada por el Jurado a su exclusivo criterio.</p>
        <ol start="9">
            <li><strong><u>Alcance de los premios:</u></strong>Los premios no incluyen otro bien o servicio adicional. El Ganador M&aacute;ximo y/o los Ganadores, no podr&aacute;n negociar ning&uacute;n Premio, ni exigir el cambio del Premio que les sea asignado por otro, ni por un bien distinto al indicado, ni por su valor en dinero. Los Premios son intransferibles, y &uacute;nica y exclusivamente podr&aacute;n ser entregados -y utilizados por- quienes resultaren efectivamente Ganadores. En el caso del Viaje a la Final, el acompa&ntilde;ante no podr&aacute; gozar del Premio asignado en favor del Ganador M&aacute;ximo si este no viajare.&nbsp;Los Premios no incluyen ninguna prestaci&oacute;n, pago, bien o servicio distinto de los expresamente indicados y enumerados en estas Bases y sus ganadores no podr&aacute;n solicitar su sustituci&oacute;n por dinero ni por otros bienes o servicios.</li>
        </ol>
        <p>Cualquier modificaci&oacute;n en el programa de premios inicialmente previsto, que signifique la incorporaci&oacute;n de nuevos premios, implicar&aacute; su autom&aacute;tica ampliaci&oacute;n.</p>
        <ol start="10">
            <li><strong><u>Consulta On Line:</u></strong>Estas Bases podr&aacute;n ser consultadas en el Sitio Web,&nbsp;<a target="_blank" href="https://www.heineken.com/ar/es/champions">https://www.heineken.com/ar/es/champions</a>.</li>
        </ol>
        <ol start="11">
            <li><strong><u>Probabilidades:</u></strong> En el presente Concurso no interviene el azar en la elecci&oacute;n de los ganadores por lo que no es posible determinar las probabilidades de ganar de los Participantes. La probabilidad de ganar los premios est&aacute; sujeta que la respuesta a la Pregunta brindada por los Participantes sea elegida como ganadora por el Jurado conforme los criterios enunciados en estas Bases.&nbsp;</li>
        </ol>
        <ol start="11">
            <li><strong><u>Prohibici&oacute;n de Medios Rob&oacute;ticos:</u></strong>Est&aacute; prohibido y ser&aacute; anulado cualquier intento o m&eacute;todo de participaci&oacute;n en el Concurso que se realice por cualquier proceso, t&eacute;cnica o mec&aacute;nica de participaci&oacute;n distinta a la detallada estas Bases. La utilizaci&oacute;n de t&eacute;cnicas de naturaleza rob&oacute;tica, repetitiva, autom&aacute;tica, programada, mecanizada o similar llevar&aacute; a la descalificaci&oacute;n del Participante.</li>
        </ol>
        <ol start="12">
            <li><strong><u>Impuestos:</u></strong>Todo impuesto, tasa o contribuci&oacute;n que deba tributarse, toda suma de dinero que deba pagarse al estado nacional, sociedades del estado, provincias o municipalidades por el hecho del ofrecimiento, asignaci&oacute;n o entrega de los premios o con motivo de la organizaci&oacute;n o difusi&oacute;n del Concurso, y los gastos en que incurran los Participantes para su traslado y estad&iacute;a cuando concurran a reclamar la asignaci&oacute;n o a retirar los premios ser&aacute; a su exclusivo cargo, a excepci&oacute;n de los expresamente asumidos por el Organizador en estas Bases.</li>
        </ol>
        <ol start="13">
            <li><strong><u>Uso de datos.</u></strong>En cumplimiento de lo dispuesto por el art&iacute;culo 7&deg; de la ley 25.326 se informa que: a. Ninguna persona puede ser obligada a proporcionar datos sensibles. b. Los datos sensibles s&oacute;lo pueden ser recolectados y objeto de tratamiento cuando medien razones de inter&eacute;s general autorizadas por ley. Tambi&eacute;n podr&aacute;n ser tratados con finalidades estad&iacute;sticas o cient&iacute;ficas cuando no puedan ser identificados sus titulares. c. Queda prohibida la formaci&oacute;n de archivos, bancos o registros que almacenen informaci&oacute;n que directa o indirectamente revele datos sensibles. El Organizador se compromete a no utilizar los datos recolectados con otro fin distinto al objeto de la presente Concurso. Proceder&aacute; a destruir la totalidad de los datos y/o registros que se obtuvieran pasado un a&ntilde;o de la fecha l&iacute;mite de entrega de premios. d.&nbsp;El titular de los datos personales tiene la facultad de ejercer el derecho de acceso a los mismos en forma gratuita&nbsp;en intervalos seriores a seis (6) meses, salvo que se acredite un inter&eacute;s leg&iacute;timo al efecto, conforme lo establecido en el art&iacute;culo 14, inciso 3 de la Ley N&ordm; 25.326 (Disposici&oacute;n 10/2008, art&iacute;culo 1&ordm;, B.O. 18/09/2008). La Direcci&oacute;n Nacional de Protecci&oacute;n de Datos Personales, &oacute;rgano de control de la Ley N&ordm; 25.326, tiene la atribuci&oacute;n de atender las denuncias y reclamos que se interpongan con relaci&oacute;n al cumplimiento de las normas sobre datos personales. Al participar en el Concurso y facilitar sus Datos Personales al Auspiciante, los Participantes prestan expreso consentimiento para que tales datos puedan ser utilizados por el Auspiciante con fines publicitarios y de marketing en general, pudiendo ser contactados por el Auspiciante u Organizador para nuevos eventos / concursos o promociones. La informaci&oacute;n de los Participantes ser&aacute; tratada en los t&eacute;rminos previstos por la Ley Nacional de Protecci&oacute;n de Datos Personales, N&ordm; 25.326. El titular de los datos podr&aacute; solicitar el retiro o bloqueo de su nombre de la base de datos, llamando al tel&eacute;fono (011)&nbsp;4115-6565, de lunes a viernes, en d&iacute;as h&aacute;biles, de 10:00 hs. a 17:00 hs..</li>
            <li><strong><br /> 14.</strong><strong><u>Garant&iacute;as y Responsabilidad</u></strong><u>:</u>El Organizador y/o sus accionistas, y/o directores, y/o gerentes, y/o funcionarios y/o su personal no otorgan garant&iacute;as de calidad, funcionamiento, ni ninguna otra en relaci&oacute;n a los Premios, debiendo dirigir cualquier reclamo a sus fabricantes y/o proveedores y/o importadores.&nbsp;El Organizador y/o sus accionistas, y/o directores, y/o gerentes, y/o funcionarios y/o su personal no ser&aacute;n responsables (i) por ning&uacute;n da&ntilde;o o perjuicio, de cualquier tipo que fuere, que pudieren sufrir los Potenciales Ganadores, Ganadores y/o Ganador M&aacute;ximo y/o terceros, en sus personas o bienes, con motivo de, o con relaci&oacute;n a, su participaci&oacute;n en el Concurso o a la utilizaci&oacute;n de los Premios; ni (ii) por fallas en la redes telef&oacute;nicas o servicios de internet, desperfectos t&eacute;cnicos, errores humanos o acciones deliberadas de terceros que pudieran interrumpir o alterar el normal desarrollo del Concurso. No se aceptar&aacute;n reclamos de los Participantes por problemas de conexi&oacute;n en los equipos de inform&aacute;tica que imposibiliten la participaci&oacute;n de acuerdo a las condiciones establecidas en las presentes Bases. Los Participantes exoneran de responsabilidad al Organizador por el uso indebido de los datos suministrados por parte de terceros. El Organizador no vender&aacute; o ceder&aacute; los datos suministrados sin autorizaci&oacute;n de los Participantes.</li>
        </ol>
        <p>Los Participantes por el s&oacute;lo hecho de participar en el Concurso garantizan:&nbsp;(i)&nbsp;que son &uacute;nicos y exclusivos responsables por los Datos Personales y Respuestas que suministren y (ii)&nbsp;que mantendr&aacute;n indemne al Organizador de las consecuencias de cualquier reclamo que estos pudieran recibir con relaci&oacute;n a o con motivo de la informaci&oacute;n de tales Datos Personales y Respuestas.&nbsp;Ser&aacute;n excluidos del Concurso aquellos Participantes que hubieren proporcionado datos falsos, inexactos y/o incompletos.&nbsp;El Organizador podr&aacute; prohibir la participaci&oacute;n en el Concurso como as&iacute; tambi&eacute;n descalificar y no otorgar Premios a las personas que intenten hacer trampas, fraudes, enga&ntilde;os o cualquier otra pr&aacute;ctica destinada a procurar ganar de forma ileg&iacute;tima, molestar, amenazar o acosar a otros Participantes, sin perjuicio de reclamarles los da&ntilde;os y perjuicios irrogados como consecuencia de dicho proceder.</p>
        <p>&nbsp;El Organizador no tiene responsabilidad alguna en la organizaci&oacute;n de los encuentros de la &ldquo;UEFA Champions League&rdquo;. Consecuentemente, no ser&aacute; responsable en el caso de que los organizadores de la misma decidan suspender los partidos, cambiarlos de fecha, de horarios ni de cualquier otra modificaci&oacute;n ni de reclamos que efect&uacute;en los Ganadores derivados de la organizaci&oacute;n de la Champions League. Por ello, los Ganadores renuncian a efectuar cualquier reclamo con base en alguno de los supuestos descriptos precedentemente. Asimismo, el Organizador no tendr&aacute; ning&uacute;n tipo de responsabilidad por los da&ntilde;os directos y/o indirectos que pudiera sufrir el Ganador M&aacute;ximo y su acompa&ntilde;ante durante el Viaje y/o en ocasi&oacute;n del mismo.</p>
        <p>El Organizador no tiene control ni responsabilidad alguna sobre medidas que pudieren dictarse a nivel nacional y/o internacional consecuencia de la pandemia COVID 19 y/o cualquier otra por lo que no ser&aacute; responsable por ninguna modificaci&oacute;n y/o suspensi&oacute;n y/o cancelaci&oacute;n del presente Concurso como as&iacute; tampoco de medidas o acciones que deba cumplir el Ganador M&aacute;ximo que tengan causa en resolucionesdictadas por autoridades nacionales y/o internacionales.</p>
        <p>Los titulares de los&nbsp;locales&nbsp;en los que se comercializan los productos de la marca Heineken&nbsp;no intervienen en la organizaci&oacute;n ni desarrollo ni patrocinan, avalan ni administran&nbsp;el Concurso, ni est&aacute;n asociados a ella. Cualquier pregunta, comentario o queja en relaci&oacute;n con&nbsp;el Concurso&nbsp;deber&aacute; remitirse al Organizador. Los titulares de&nbsp;tales locales no ser&aacute;n responsables del cumplimiento de los compromisos que asume el Organizador en estas Bases y los Potenciales Ganadores deber&aacute;n reclamar la entrega de los Premios exclusivamente al Organizador.</p>
        <ol start="15">
            <li><strong><u>Aceptaci&oacute;n y autorizaci&oacute;n:</u></strong>Los Potenciales Ganadores y/o los Ganadores y/o el Ganador M&aacute;ximo y/o participantes, autorizan al Organizador y/o a su agencia de publicidad a difundir, por el s&oacute;lo hecho de su participaci&oacute;n y como condici&oacute;n para la asignaci&oacute;n de los Premios, los datos personales, domicilios, im&aacute;genes y voces, con fines comerciales, en los medios y formas que el Organizador disponga, sin derecho a compensaci&oacute;n alguna, durante el Plazo de Vigencia y hasta tres a&ntilde;os de finalizado el Concurso.</li>
        </ol>
        <p>Asimismo, los ganadores del Premio &ldquo;Viaje La Final&rdquo; se comprometen a permitir ser fotografiados y filmados durante el Viaje. De igual manera, los ganadores de los Premios Adicionales se comprometen a dejarse fotografiar al retirar el premio que les fuere asignado. El Organizador podr&aacute; utilizar las fotograf&iacute;as y filmaciones con fines comerciales, en los medios y formas que disponga a su exclusivo criterio, sin derecho a compensaci&oacute;n alguna, durante el Plazo de Vigencia y hasta tres a&ntilde;os de finalizado el Concurso.</p>
        <ol start="16">
            <li><strong><u>Difusi&oacute;n:</u></strong>El Concurso ser&aacute; difundido mediante material publicitario exhibido en los puntos de venta, publicidad televisiva, gr&aacute;fica y digital.</li>
        </ol>
        <ol start="17">
            <li><strong><u>Fuero y Competencia:</u></strong>Para cualquier cuesti&oacute;n judicial que pudiera derivarse de la realizaci&oacute;n del Concurso, los Participantes y el Organizador se someter&aacute;n a la jurisdicci&oacute;n de los tribunales ordinarios nacionales con asiento en la Ciudad de Buenos Aires.</li>
        </ol>
        <ol start="18">
            <li><strong><u>Consentimiento:</u></strong>La mera Participaci&oacute;n en el Concurso implica la total e irrestricta aceptaci&oacute;n y conocimiento de las presentes Bases y de todas sus condiciones. Asimismo, la Participaci&oacute;n implica el reconocimiento de las decisiones que el Organizador tome con relaci&oacute;n al Concurso como de car&aacute;cter definitivo e inapelable</li>
        </ol>
        <ol start="19">
            <li>Compa&ntilde;&iacute;a Industrial Cervecera S.A.&nbsp;no&nbsp;es&nbsp;sponsor&nbsp;de la UEFA&nbsp;Champions League.</li>
        </ol>
        <div class="text-center">
            <p><strong>BEBER CON MODERACI&Oacute;N. PROHIBIDA SU VENTA A MENORES DE 18 A&Ntilde;OS</strong></p>
        </div>
    </div>
</section>

@endsection